# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pred_dens_mix_approx <- function(x_test, y_test, theta_sr, beta_mean, sig2_samp, sv, sv_phi, sv_mu, sv_sigma2, chol_C_N_inv_samp, m_N_samp, M, log) {
    .Call(`_PARCORwMNIGDF_pred_dens_mix_approx`, x_test, y_test, theta_sr, beta_mean, sig2_samp, sv, sv_phi, sv_mu, sv_sigma2, chol_C_N_inv_samp, m_N_samp, M, log)
}

do_shrinkTVP_mNIG <- function(y, x, a0, K, niter, nburn, nthin, c0, g0, G0, eta2_d1, eta2_d2, p_d1, p_d2, par_c, display_progress, ret_beta_nc, store_burn, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, SAVS, delta) {
    .Call(`_PARCORwMNIGDF_do_shrinkTVP_mNIG`, y, x, a0, K, niter, nburn, nthin, c0, g0, G0, eta2_d1, eta2_d2, p_d1, p_d2, par_c, display_progress, ret_beta_nc, store_burn, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, SAVS, delta)
}

